### ISSUE TITLE
Preline.js doesn't work in production - SvelteKit

### ISSUE THREAD

**Issue by digitaldrreamer** [htmlstreamofficial/preline#110]
Whenever I build SvelteKit, preline.js in the _node_modules_ file is not bundled with it.

I found a workaround for this: copy the preline.js from the _node_modules_ file into the _/static_ folder and link to it in the index.html with _%sveltekit.assets%/preline.js_. It works this way.

But **this** should be in the docs.

**Comment by Codes-Wizard** [comment]
Perhaps before the "Add the Preline UI JavaScript" section, there should be a section to copy the preline.js file via cli (since they'll be using the terminal for the setup anyway)

Something like this:

3.
Run this command in your terminal. Make sure you're in the root directory of your svelte project first. You can navigate by using `cd /yourProjectDirectory`. This command copies the script file to your svelte static folder.

On Windows:
```
copy ./node_modules/preline/dist/preline.js
```
On Linux and Mac:
```
cp ./node_modules/preline/dist/preline.js ./static/preline/
```
4.
Add the Preline UI JavaScript
Include the JavaScript <script> that powers the interactive elements near the end of your <body> tag:
```
// app.html
<script src="/script/preline/dist/preline.js"></script>
```
This works for me🙂

**Comment by kevan-mtl** [comment]
Works for me, but shouldn't step 4 be based on your step 3?
`<script src="%sveltekit.assets%/preline/preline.js"></script>`

**Comment by Codes-Wizard** [comment]
> Works for me, but shouldn't step 4 be based on your step 3?
> `<script src="%sveltekit.assets%/preline/preline.js"></script>`

@kevan-mtl Yes. Sorry about the confusion. It is based on step 3.

**Comment by Codes-Wizard** [comment]
> Works for me, but shouldn't step 4 be based on your step 3?
> `<script src="%sveltekit.assets%/preline/preline.js"></script>`

@kevan-mtl Thanks. I saw the mistake. Fixed it.

**Comment by Mr-Zafar** [comment]
@kevan-mtl marking it as closed for now. If you have more details to share in the future, feel free to open a new issue.
