### ISSUE TITLE
Preline does not work in production with vercel edge and Qwikcity

### ISSUE THREAD

**Issue by harshmangalam** [htmlstreamofficial/preline#124]
loading script only work in development not in production

```js
<script src="./node_modules/preline/dist/preline.js"></script>
```

Provide helper function to load script on render in browser using `useVisibleTask$`

**Comment by jahaganiev** [comment]
It doesn't seem preline.js explicit issue and should be included in preline.js file. We have update Qwik docs [here](https://preline.co/docs/frameworks-qwik.html) - please feel free to let us know what can be improved with some before and after sample codes.

Meanwhile, closing the issue until we've more precise details with some examples.

Cheers!

**Comment by dejurin** [comment]
> For anyone stumbling here as well, here's how you can load the full bundle:
> 
> ```ts
> useVisibleTask$(async () => {
>     const { HSStaticMethods } = await import("preline");
>     HSStaticMethods.autoInit();
> });
> ```
> 
> or to load specific plugins (to minimize bundle size):
> 
> ```ts
> useVisibleTask$(async () => {
>     const { default: HSTooltip } = await import("preline/dist/tooltip");
>     HSTooltip.autoInit();
> });
> ```
> 
> you probably want this on your `src/root.tsx` so its loaded right away. You have to call `autoInit` manually because preline uses `window.addEventListener('load', ...)` where your component might not be mounted yet.
> 
> HTH.

Caution: The useVisibleTask$() should be used as a last resort, because it eagerly executes code on the client. Qwik through [resumability](https://qwik.builder.io/docs/components/tasks/) goes out of its way to delay the execution of code on the client, and useVisibleTask$() is an escape hatch that should be used with caution.

**When in doubt, instead of "useVisibleTask$()" use**:

useOn() -> listen to events on the root element of the current component.
useOnWindow() -> listen to events on the window object.
useOnDocument() -> listen to events on the document object.

**Comment by marconi** [comment]
@dejurin The thing is, these `useOn*` only runs on initial load. On an SPA, where you only want to load the plugins on certain pages these events won't fire again and so the plugins won't get initialized. Maybe a better way is to use `useTask$` + `isBrowser`.
