### ISSUE TITLE
Next 13 / Install only Plugin/Modal

### ISSUE THREAD

**Issue by thefubon** [htmlstreamofficial/preline#66]
Please tell me how to connect only Modal in Next 13. The Plugins page says to install not all Preline but only npm i @preline/overlay. I did but nothing works. 

https://preline.co/plugins/html/modal.html

**Comment by ybelakov** [comment]
same issue here with tooltip plugin

**Comment by jahaganiev** [comment]
Hey @thefubon, @ybelakov - in order to use any Preline JavaScript plugins you still need to install/download Preline package and link the plugin and overlay (or any plugin name you are using) files in the tailwind config file. 

We will include related script in the next updates for each plugins and improve our docs with more Getting Started guides for individual plugins.

Meanwhile, please have a look working live playground Overlay (Modal) demo for Next.js 13: https://stackblitz.com/edit/preline-overlay-nextjs?file=tailwind.config.js

Cheers!
Jaha

**Comment by ybelakov** [comment]
Thank you for the fast response! I see I have to link the node modules lol location in the content array. However I am using yarn PnP which does not work with node_modules but rather yarn cache archives. I know this is not specifically related to your package, but still will be useful if you can help me out.

**Comment by jahaganiev** [comment]
Hey @ybelakov, if you are not using NPM then you may download Preline UI sources from Github and include in your project.

Hope that helps!

Cheers!
Jaha

**Comment by Mr-Zafar** [comment]
@ybelakov @thefubon  it as closed for now. If you have more details to share in the future, feel free to open a new issue.
