### ISSUE TITLE
hs-dropdown-open:rotate-180 no longer works for the arrow in dropdown

### ISSUE THREAD

**Issue by sevin** [htmlstreamofficial/preline#82]
When the dropdown is opened, the arrow no longer rotate 180 degrees.
This behaviour could also be seen at the example of its own documentation page https://preline.co/plugins/html/dropdown.html

**Comment by jahaganiev** [comment]
Hey @sevin! This feature has never been available by design. However, if you would like to have it you may modify the plugin file. 

You should add the following code here https://github.com/htmlstreamofficial/preline/blob/main/plugin.js#L18

```
({ modifySelectors, separator }) => {
  modifySelectors(({ className }) => {
    return `.hs-dropdown.active > .hs-dropdown-toggle .${e(`hs-dropdown-active${separator}${className}`)}`;
  });
},
```

The final code should look like this:

```
addVariant('hs-dropdown-open', [
  ({ modifySelectors, separator }) => {
    modifySelectors(({ className }) => {
      return `.hs-dropdown.open > .${e(`hs-dropdown-open${separator}${className}`)}`;
    });
  },
  ({ modifySelectors, separator }) => {
    modifySelectors(({ className }) => {
      return `.hs-dropdown.active > .hs-dropdown-toggle .${e(`hs-dropdown-active${separator}${className}`)}`;
    });
  },
  ({ modifySelectors, separator }) => {
    modifySelectors(({ className }) => {
      return `.hs-dropdown.open > .hs-dropdown-menu > .${e(`hs-dropdown-open${separator}${className}`)}`;
    });
  },
]);
```

Hope that helps!

Cheers!

**Comment by MangoMarcus** [comment]
@jahaganiev If this feature was never available by design then why is it used in the [documentation examples](https://preline.co/plugins/html/dropdown.html)?

<img width="797" alt="Screenshot 2023-10-05 at 19 57 13" src="https://github.com/htmlstreamofficial/preline/assets/72021142/78479ea7-2a25-4ce4-9d1c-871ca108b054">

For anyone else coming from Google, I've managed to get around it using Tailwind's [group](https://tailwindcss.com/docs/hover-focus-and-other-states#styling-based-on-parent-state) class and the `open` class which Preline adds, like this

```html
<div class="hs-dropdown group">
  <button type="button" class="hs-dropdown-toggle">
    Actions
    <svg class="group-[.open]:rotate-180">
      <!-- ... -->
    </svg>
  </button>
  <!-- ... -->
```

So, rotate the icon when `hs-dropdown` has the `open` class. This does the job nicely, but it's not ideal as `open` doesn't seem to be documented anywhere

**Comment by jahaganiev** [comment]
Hey @MangoMarcus - dropdowns are now by default includes rotate feature. Thanks!
